"""empty message

Revision ID: 2dab71c3cc5b
Revises: 61edb4f3b2fb
Create Date: 2021-01-23 23:40:48.695298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dab71c3cc5b'
down_revision = '61edb4f3b2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_name_key', 'Artist', type_='unique')
    op.drop_constraint('Venue_name_key', 'Venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Venue_name_key', 'Venue', ['name'])
    op.create_unique_constraint('Artist_name_key', 'Artist', ['name'])
    # ### end Alembic commands ###
