"""empty message

Revision ID: 61edb4f3b2fb
Revises: 72c8286387a2
Create Date: 2021-01-23 23:39:41.217992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61edb4f3b2fb'
down_revision = '72c8286387a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['name'])
    op.create_unique_constraint(None, 'Venue', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
